services:
  its-gerencial-casan:
    build: .
    container_name: its-gerencial-casan
    restart: unless-stopped

  its-email-service:
    build: ./email-service
    container_name: its-email-service
    restart: unless-stopped
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
